#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Freifunk_Generic >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Freifunk_Generic=/luci-static/freifunk-generic
		set luci.main.mediaurlbase=/luci-static/freifunk-generic
		commit luci
	EOF
fi

exit 0
