#
# Copyright (C) 2020 OpenWrt.org
# 流量统计
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-wrtbwmon-zh
LUCI_PKGARCH:=all
PKG_VERSION:=v0.8.9
PKG_RELEASE:=1
LUCI_DEPENDS:=+wrtbwmon
LUCI_TITLE:=LuCI support for Wrtbwmon

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
