name: API
on:
  workflow_dispatch:

  schedule:
   - cron: 35 4 * * *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: API
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    
    steps:
    - name: 密匙检测（密匙为空则退出）
      run: |
        if [[ -z "${{ secrets.REPO_TOKEN }}" ]]; then
          echo "您没有设置仓库密匙，请按教程设置好密匙再来"
          echo "REPO_TOKEN密匙制作教程：https://git.io/jm.md"
          exit 1
        fi
    
    - name: 准备结束
      uses: actions/checkout@v3
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y git git-core wget curl
        sudo timedatectl set-timezone "$TZ"
        
    - name: API
      if: steps.regular.outcome == 'success' && env.UPDATE_FIRMWARE_ONLINE == 'true' && env.REPO_TOKEN
      run: |
        mkdir -p Github_Api
        cd Github_Api
        wget -q --no-check-certificate https://api.github.com/repos/ophub/kernel/contents/pub/stable -O stable.api
        if [[ $? -ne 0 ]]; then
          curl -fsSL https://api.github.com/repos/ophub/kernel/contents/pub/stable -O stable.api
        fi
        wget -q --no-check-certificate https://api.github.com/repos/vernesong/OpenClash/contents/core-lateset/premium -O premium.api
        if [[ $? -ne 0 ]]; then
          curl -fsSL https://api.github.com/repos/vernesong/OpenClash/contents/core-lateset/premium -o premium.api
        fi
        
    - name: API
      uses: ncipollo/release-action@main
      with:
        name: API
        tag: API
        token: ${{ secrets.REPO_TOKEN }}
        artifacts: "Github_Api/*"
        allowUpdates: true
