#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service()
{
	procd_open_instance
	procd_set_param command /usr/sbin/qmodem-settings watch
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service()
{
	/usr/sbin/qmodem-settings apply-all >/dev/null 2>&1 &
}

service_triggers()
{
	procd_add_reload_trigger qmodem qmodem_voip
}
