#!/bin/sh /etc/rc.common
# Copyright (C) 2019 [CTCGFW] Project OpenWRT

START=90
STOP=10

addr_type="$(uci get filebrowser.config.addr_type)"
db_dir="$(uci get filebrowser.config.db_dir)"
[ "${db_dir}" == "/" ] || db_dir="${db_dir%*/}"
db_name="$(uci get filebrowser.config.db_name| sed 's#/##g')"
enabled="$(uci get filebrowser.config.enabled)"
port="$(uci get filebrowser.config.port)"
root_dir="$(uci get filebrowser.config.root_dir)"
username="$(uci get filebrowser.config.username)"
password="$(uci get filebrowser.config.password)"

if [ "${addr_type}" == "local" ];then
	addr="127.0.0.1"
elif [ "${addr_type}" == "lan" ];then
	addr="$(uci get network.lan.ipaddr)"
elif [ "${addr_type}" == "wan" ];then
	addr="0.0.0.0"
fi

start() {
	stop
	[ "$enabled" == "1" ] || exit 0
	mkdir -p "${root_dir}"
	mkdir -p "${db_dir}"
        filebrowser -d "${db_dir}/${db_name}" config init
        filebrowser -d "${db_dir}/${db_name}" config set --locale zh-cn
        filebrowser -d "${db_dir}/${db_name}" users add "${username}" "${password}" --perm.admin
	filebrowser -a "${addr}" -d "${db_dir}/${db_name}" -p "${port}" -r "${root_dir}" >/dev/null 2>&1 &
}

stop() {
	killall filebrowser >/dev/null 2>&1
}
