#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service()
{
	mkdir -p -m 700 /etc/qmodem_voip
	mkdir -p -m 700 /var/run/qmodem_voip
	mkdir -p -m 700 /var/lib/qmodem_voip
	interface=$(uci -q get qmodem_voip.main.interface)
	interface=${interface:-lan}
	case $interface in ''|*[!A-Za-z0-9_.:-]*) return 1 ;; esac
	media_socket_path=$(uci -q get qmodem_voip.main.media_socket_path)
	media_socket_path=${media_socket_path:-/var/run/qmodem_voip/media.sock}
	enabled=$(uci -q get qmodem_voip.main.enabled)
	case $enabled in 1) ;; *) enabled=0 ;; esac
	procd_open_instance
	procd_set_param command /usr/sbin/qmodem_voip_daemon_wait \
		--media-interface "$interface" \
		--media-cert /dev/null \
		--media-key /dev/null \
		--media-socket-path "$media_socket_path" \
		--start-enabled "$enabled"
	procd_set_param respawn 3600 5 5
	procd_close_instance
	/usr/sbin/qmodem_voip_web
}

reload_service()
{
	stop
	start
	/usr/sbin/qmodem_voip_web
}

service_triggers()
{
	procd_add_reload_trigger qmodem_voip
}
