#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@filebrowser[-1]
	add ucitrack filebrowser
	set ucitrack.@filebrowser[-1].init=filebrowser
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0