#!/bin/sh /etc/rc.common
START=92
USE_PROCD=1

start_service()
{
	local database
	config_load qmodem_sms
	config_get database main database /etc/qmodem/sms.sqlite3
	mkdir -p "$(dirname "$database")"
	procd_open_instance
	procd_set_param command /usr/sbin/qmodem-smsd "$database"
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/qmodem /etc/config/qmodem_sms
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger qmodem qmodem_sms
}
