#!/bin/sh

legacy=$(uci -q get qmodem_voip.sip)
[ -n "$legacy" ] || exit 0

copy_option()
{
	local source="$1" destination="$2" value
	value=$(uci -q get "$source")
	[ -n "$value" ] || return 0
	uci -q set "$destination=$value"
}

mode=$(uci -q get qmodem_voip.sip.mode)
[ "$mode" = outbound ] && direction=outbound || direction=inbound
enabled=$(uci -q get qmodem_voip.sip.enabled)
enabled=${enabled:-0}

uci -q set "qmodem_sip.$direction.enabled=$enabled"
copy_option qmodem_voip.sip.interface "qmodem_sip.$direction.interface"
copy_option qmodem_voip.sip.media_socket_path qmodem_sip.main.media_socket_path
copy_option qmodem_voip.sip.rtp_start qmodem_sip.main.rtp_start
copy_option qmodem_voip.sip.rtp_end qmodem_sip.main.rtp_end

if [ "$direction" = outbound ]; then
	copy_option qmodem_voip.sip.outbound_server qmodem_sip.outbound.server
	copy_option qmodem_voip.sip.outbound_port qmodem_sip.outbound.port
	copy_option qmodem_voip.sip.outbound_transport qmodem_sip.outbound.transport
	copy_option qmodem_voip.sip.outbound_username qmodem_sip.outbound.username
	copy_option qmodem_voip.sip.outbound_password qmodem_sip.outbound.password
	copy_option qmodem_voip.sip.outbound_realm qmodem_sip.outbound.realm
	copy_option qmodem_voip.sip.outbound_register_interval \
		qmodem_sip.outbound.register_interval
else
	copy_option qmodem_voip.sip.username qmodem_sip.inbound.username
	copy_option qmodem_voip.sip.password qmodem_sip.inbound.password
fi

uci -q commit qmodem_sip || exit 1
chmod 600 /etc/config/qmodem_sip
uci -q delete qmodem_voip.sip
uci -q commit qmodem_voip
uci -q delete firewall.qmodem_voip
uci -q commit firewall

exit 0
